import time
import random

from state import GameState # Ensure state.py is in the same directory, or change to modules.state
from modules.cardplay import response_type

def trigger_random_event(cash):
    """Introduces random life events to make the game dynamic and unpredictable."""
    events = [
        {"name": "Unexpected Textbook Cost!", "effect": -30, "type": "bad"},
        {"name": "Found money in an old jacket!", "effect": 5, "type": "good"},
        {"name": "That friend finally paid you back!", "effect": 40, "type": "good"},
        {"name": "Flat tire on your bike. Repair costs.", "effect": -25, "type": "bad"},
        {"name": "Late night pizza craving.", "effect": -15, "type": "bad"},
    ]
    
    event = random.choice(events)
    if event["type"] != "neutral":
        print(f"RANDOM EVENT: {event['name']} (Cash impact: £{event['effect']})")
        return max(0, cash + event['effect']) 
    else:
        print(f"\nRANDOM EVENT: {event['name']}")
    return cash

def print_week_lore(week):
    if week == 1:
        print("You're a fresh student with £100 to your name. Your goal this week is simple: survive and build an Emergency Fund. Learn the safety of the bank and low-risk bonds.")
        print("FINANCE TIP: Always pay yourself first. An emergency fund stops unexpected costs from putting you in debt.")
    elif week == 2:
        print("Textbooks are expensive, and inflation is eating your cash. It's time to learn about investing to make your money work for you.")
        print("FINANCE TIP: Cash loses value over time due to inflation. Investing in assets helps you outpace it.")
    elif week == 3:
        print("You're eyeing a summer internship, but you need a bigger safety net. Let's introduce ETFs (Exchange Traded Funds) for diversified, steady growth.")
        print("FINANCE TIP: Don't put all your eggs in one basket! ETFs spread your money across many companies, lowering risk.")
    elif week == 4:
        print("Graduation is looming. You want to start building a passive retirement pot early to take advantage of compound interest.")
        print("FINANCE TIP: Compound interest is the 8th wonder of the world. Earning interest on your interest is how real wealth is built.")
    elif week == 5:
        print("The Final Boss: Financial Independence. Can you manage high-risk stocks and balance your portfolio to secure your future financial wellbeing.")
        print("FINANCE TIP: High returns usually mean high risk. A balanced portfolio ensures you can weather market crashes.")

def game_loop():
    print("Welcome to Common Pence: The Student Finance Simulator!")
    print("Your mission: Navigate 5 grueling weeks of student life, make smart financial decisions, and graduate with financial wellbeing.\n")
    time.sleep(2)
    print("You will be given a hand of 5 cards.\n")
    time.sleep(2)
    print("You can play up to 3 cards per day.\n")
    time.sleep(2)
    print("Each card will let you perform a financial decision such as running a side hustle, investing, selling etc.\n")
    time.sleep(2)
    
    # Initialize game state
    state = GameState(starting_cash=100.0)
    state.draw_new_hand() # Draw the first hand
    
    TOTAL_WEEKS = 5
    target_goal = 1000 

    while state.week <= TOTAL_WEEKS:
        
        # Week Start Lore
        if state.day == 1:
            print(f"\n{'='*45}")
            print(f"--- WEEK {state.week}: FINANCIAL MILESTONE {state.week} ---")
            print_week_lore(state.week)
            print(f"\nTarget Goal to reach by Friday: £{target_goal}")
            print(f"{'='*45}")
        
        print(f"\n--- Week {state.week}, Day {state.day} ---")
        
        # 1. Trigger random events
        state.cash = trigger_random_event(state.cash)
        
        # 2. Harvest Passive Income generated by the engine's tick
        if state.engine.store > 0:
            print(f"💰 You earned £{state.engine.store:.2f} in passive income/dividends!")
            state.cash += state.engine.store
            state.engine.store = 0 # Reset store after harvesting
        
        print(f"Starting Cash: £{state.cash:.2f}")
        print(f"Total Portfolio Value: £{state.engine.get_total():.2f}")
        print(f"Total Wealth: £{state.get_total_wealth():.2f}")
        
        # Action Phase Loop
        while state.actions_left > 0 and state.current_hand:
            print(f"\n--- Actions Left: {state.actions_left} ---")
            print(f"Current Cash: £{state.cash:.2f}")
            print("1. Make a Financial Decision (Play a Card)")
            print("2. Hold Positions (End Day early)")
            
            choice = input("What would you like to do? (1/2): ")
            
            if choice == '1':
                print("\nYour Hand for Today:")
                for idx, c in enumerate(state.current_hand):
                    print(f"{idx}. {c.name}")
                
                try:
                    card_choice = int(input("\nSelect an opportunity to pursue (number): "))
                    
                    if card_choice < 0 or card_choice >= len(state.current_hand):
                        raise ValueError("Card choice out of range.")
                        
                    # Pop the card so it is removed from the hand once played
                    selected_card = state.current_hand.pop(card_choice)
                    selected_card.engine = state.engine
                    
                    # Capture the response to update player cash
                    response = selected_card.play_card(state.cash)
                    print(f"\n>>> {response.text}")
                    
                    if response.response_type == response_type.INVEST:
                        state.cash -= response.value
                    elif response.response_type == response_type.SELL:
                        state.cash += response.value
                    elif response.response_type == response_type.INSTANT:
                        state.cash += response.value
                    
                    state.actions_left -= 1
                    
                except (ValueError, IndexError):
                    print("Invalid decision. You fumbled your hand and wasted an action!")
                    state.actions_left -= 1
                    
            elif choice == '2':
                print("You decided to hold your positions and let the market do its work.")
                break  # Exit the action loop and move to market tick
            else:
                print("Invalid choice. Try again.")
        
        if state.actions_left == 0:
            print("\nYou're out of actions for today!")
        
        # 3. Market moves at the end of the day
        state.engine.tick()
        time.sleep(1) 
        
        # 4. End of week review
        if state.day == 5:
            print(f"\n{'*'*45}")
            print(f"--- END OF WEEK {state.week} PERFORMANCE REVIEW ---")
            
            final_wealth = state.get_total_wealth()
            print(f"Final Wealth: £{final_wealth:.2f} / Target Milestone: £{target_goal}")
            
            if final_wealth >= target_goal:
                print("Congratulations! You made smart financial decisions and hit your milestone.")
                time.sleep(2)
            else:
                print("DEBT TRAP! You failed to meet your financial milestone.")
                print(f"You managed your finances well for {state.week - 1} weeks, but poor financial knowledge caught up to you.")
                print("Remember: Financial wellbeing comes from making the right financial decisions.")
                return 
                
        # 5. Move to the next day
        state.advance_day()
            
    print("\nYOU WON!🏆")
    print("You survived all 5 weeks, built a strong portfolio, and learned the power of compounding!")

if __name__ == "__main__":
    game_loop()
